# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- adf_publish

pool:
  vmImage: ubuntu-latest

variables:
  subscriptionId : 4a7ae167-f098-47b4-9017-a6cbad3a0abe
  resourceGroupName: test1
  dataFactoryName: chejuroADF

steps:
- task: UseNode@1
  inputs:
    version: '16.x'  # Specify the Node.js version you need
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: |
     pwd 
     ls /home/vsts/work/1/s/'

- task: Npm@1
  displayName: 'Install ADF Utilities'
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
    verbose: true

- script: |
    npx @microsoft/azure-data-factory-utilities validate "$(Build.SourcesDirectory)" "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryName)"
    npx @microsoft/azure-data-factory-utilities export "$(Build.SourcesDirectory)" "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryName)" "$(Build.ArtifactStagingDirectory)/adf_arm"
  displayName: 'Validate and Export ADF ARM Templates'


- task: PublishBuildArtifacts@1
  displayName: 'Publish ADF ARM Templates'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/adf_arm'
    artifactName: 'ADF_ARM_Templates'
    publishLocation: 'Container'
